### ISSUE TITLE
Add an option to instead show recent albums

### ISSUE THREAD

**Issue by dejalavidavolar** [crackheadakira/lastFMEmbed#3]
Hi, this is an awesome tool! Thanks for your work on it. I would like to suggest an option to show recent albums instead of last songs. 

Have a nice day/night!

**Comment by crackheadakira** [comment]
Hey! I'm glad to hear you like the site! And just to make sure, instead of "Norwegian Wood - The Beatles", it would be "Rubber Soul - The Beatles"?

**Comment by dejalavidavolar** [comment]
I was thinking something like this:
![Screenshot 2024-07-16 at 18-31-56 _now • Robb Knight](https://github.com/user-attachments/assets/b669925f-8650-4371-bb36-94e85b373008)

Source: https://rknight.me/now/

In that website, Rob uses https://github.com/rknightuk/api/blob/main/services/lastfm.js
Maybe it is something similar? I don't know of coding.

Greetings!

**Comment by crackheadakira** [comment]
Hey! There's now 2 new parameters
`showAsAlbum=true`
![2024-07-17_14-42](https://github.com/user-attachments/assets/4ac5a06f-303e-4d14-8b8c-c7149e405ece)

and `showOnlyCover=true`
![2024-07-17_14-42_1](https://github.com/user-attachments/assets/aa864c10-7c6f-4850-903a-4b2479b94d38)

**Comment by dejalavidavolar** [comment]
I love it!! Thanks for adding this feature. 

Have a nice day/night!!
